<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>pike</string>
      <string>pmod</string>
    </array>
    <key>firstLineMatch</key>
    <string>(-[*]-( [Mm]ode:)? [Pp]ike -[*]-|^#!/.*\bpike\b)</string>
    <key>foldingStartMarker</key>
    <string>(?x)
     /\*\*(?!\*)
    |^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?
    \{\s*($|//|/\*(?!.*?\*/.*\S))</string>
    <key>foldingStopMarker</key>
    <string>(?&lt;!\*)\n\*\*/|^\s*\}</string>
    <key>keyEquivalent</key>
    <string>^~C</string>
    <key>name</key>
    <string>Pike</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#preprocessor-rule-enabled</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#preprocessor-rule-disabled</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#preprocessor-rule-other</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Control flow keywords</string>
        <key>match</key>
        <string>\b(if|else|while|for|foreach|do|return|continue|break|switch|case|default|goto|catch|lambda|gauge|inherit)\b</string>
        <key>name</key>
        <string>keyword.control.pike</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(enum|float|int|typedef|void|object|class|mapping|string|array|multiset|mixed|function)\b</string>
        <key>name</key>
        <string>storage.type.pike</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Modifiers</string>
        <key>match</key>
        <string>\b(public|protected|private|static|constant)\b</string>
        <key>name</key>
        <string>storage.modifier.pike</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#sizeof</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Numeric values</string>
        <key>match</key>
        <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
        <key>name</key>
        <string>constant.numeric.pike</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Language constants</string>
        <key>match</key>
        <string>\b(UNDEFINED|__LINE__|__FILE__|true|false)\b</string>
        <key>name</key>
        <string>constant.language.pike</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.pike</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?:(?&lt;=\\\\)|(?&lt;!\\))\"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.pike</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.pike</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_placeholder</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.pike</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.pike</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.pike</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?x)
                 ^\s*\#\s*(define)\s+           # define
                 ((?&lt;id&gt;[a-zA-Z_][a-zA-Z0-9_]*))    # macro name
                 (?:                                # and optionally:
                   (\()                            # an open parenthesis
                     (
                       \s* \g&lt;id&gt; \s*            # first argument
                       ((,) \s* \g&lt;id&gt; \s*)*     # additional arguments
                       (?:\.\.\.)?               # varargs ellipsis?
                     )
                   (\))                             # a close parenthesis
                 )?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.define.pike</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.preprocessor.pike</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.pike</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.preprocessor.pike</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.parameters.pike</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.pike</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(?://|/\*))|$</string>
        <key>name</key>
        <string>meta.preprocessor.macro.pike</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&gt;\\\s*\n)</string>
            <key>name</key>
            <string>punctuation.separator.continuation.pike</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$base</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*#\s*(error|warning)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.error.pike</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>meta.preprocessor.diagnostic.pike</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&gt;\\\s*\n)</string>
            <key>name</key>
            <string>punctuation.separator.continuation.pike</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*#\s*(include)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.include.pike</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(?://|/\*))|$</string>
        <key>name</key>
        <string>meta.preprocessor.pike.include</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&gt;\\\s*\n)</string>
            <key>name</key>
            <string>punctuation.separator.continuation.pike</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.pike</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.pike</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.include.pike</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>&lt;</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.pike</string>
              </dict>
            </dict>
            <key>end</key>
            <string>&gt;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.pike</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.other.lt-gt.include.pike</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*#\s*(define|defined|elif|else|if|ifdef|ifndef|line|pragma|undef|endif|charset)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.pike</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(?://|/\*))|$</string>
        <key>name</key>
        <string>meta.preprocessor.pike</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&gt;\\\s*\n)</string>
            <key>name</key>
            <string>punctuation.separator.continuation.pike</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>#block</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?x)
        (?:  ^                                 # begin-of-line
            |
             (?: (?= \s )           (?&lt;!else|return) (?&lt;=\w)    #  or word + space before name
               | (?= \s*[A-Za-z_] ) (?&lt;!&amp;&amp;)       (?&lt;=[*&amp;&gt;])     #  or type modifier before name
             )
        )
        (\s*) (?!(while|for|do|if|else|switch|catch|return|foreach|
                   object|int|float|function|mapping|array|multiset|
                   lambda|program|mixed|class)\s*\()
        (
          (?: [A-Za-z_`][A-Za-z0-9_]*+ | :: )++                    # actual name
        )
         \s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.function.leading.pike</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.pike</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.pike</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})|(?=#)|(;)</string>
        <key>name</key>
        <string>meta.function.pike</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bconstant\b</string>
            <key>name</key>
            <string>storage.modifier.pike</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>block</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>\}</string>
        <key>name</key>
        <string>meta.block.source.pike</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block_innards</string>
          </dict>
        </array>
      </dict>
      <key>block_innards</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.function-call.leading.source.pike</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.function.any-method.source.pike</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.source.pike</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?x)
                     (?: (?= \s )  (?:(?&lt;=else|new|return) | (?&lt;!\w)) (\s+))?
                     (\b
                      (?!(while|for|do|if|else|foreach|lambda|switch|
                          catch|enumerate|return|
                          mapping|multiset|mixed|int|float|class|function|
                          string|program|object)\s*\()
                        (?:(?!NS)[A-Za-z_][A-Za-z0-9_]*+\b | :: )++    # actual name
                     )
                     \s*(\()</string>
            <key>name</key>
            <string>meta.function-call.source.pike</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$base</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.source.pike</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.source.pike</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.source.pike</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.source.pike</string>
          </dict>
        </array>
      </dict>
      <key>parens</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>\)</string>
        <key>name</key>
        <string>meta.parens.source.pike</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$base</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.pike</string>
    <key>uuid</key>
    <string>f0c5f4ad-3e8a-4add-9ebf-2ce1d5e5262f</string>
  </dict>
</plist>