<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>source.pike</string>
    <key>foldingStopMarker</key>
    <string>(?&lt;!\*)\n\*\*/|^\s*\}</string>
    <key>foldingStartMarker</key>
    <string>(?x)/\*\*(?!\*)|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))</string>
    <key>uuid</key>
    <string>f0c5f4ad-3e8a-4add-9ebf-2ce1d5e5262f</string>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>end</key>
            <string>\*/n?</string>
            <key>begin</key>
            <string>/\*</string>
            <key>name</key>
            <string>comment.block.source.pike</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.source.pike</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.source.pike</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.source.pike</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>builtinTypes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.source.pike</string>
            <key>match</key>
            <string>(?x)\b(float|int|object|mixed|class|mapping|function|void|enum|multiset|array|string)\b</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.source.pike</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>Macro definitions</string>
        <key>name</key>
        <string>meta.preprocessor.source.pike</string>
        <key>match</key>
        <string>^(#)\s*\b(if|ifdef|ifndef|elif|else|endif|include|pike|define|warning|error)\b</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Control flow keywords</string>
        <key>name</key>
        <string>keyword.control.source.pike</string>
        <key>match</key>
        <string>\b(if|else|while|for|foreach|do|return|continue|break|switch|case|default|goto|catch)\b</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Modifiers</string>
        <key>name</key>
        <string>storage.modifier.source.pike</string>
        <key>match</key>
        <string>\b(public|protected|private|static|constant)\b</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Numeric values</string>
        <key>name</key>
        <string>constant.numeric.source.pike</string>
        <key>match</key>
        <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Language constants</string>
        <key>name</key>
        <string>constant.language.pike</string>
        <key>match</key>
        <string>\b(UNDEFINED|__LINE__|__FILE__)\b</string>
      </dict>
      <dict>
        <key>endCapture</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.pike</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\"</string>
        <key>beginCapture</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.pike</string>
          </dict>
        </dict>
        <key>begin</key>
        <string>\"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_placeholder</string>
          </dict>
        </array>
        <key>name</key>
        <string>string.quoted.double.pike</string>
      </dict>
      <dict>
        <key>endCapture</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.pike</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>beginCapture</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.pike</string>
          </dict>
        </dict>
        <key>begin</key>
        <string>'</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_escaped_char</string>
          </dict>
        </array>
        <key>name</key>
        <string>string.quoted.single.pike</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#builtinTypes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#doubleQuotedStringLiteral</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#doubleQuotedString</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#singleQuotedString</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#preprocessor-rule-enabled</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#preprocessor-rule-disabled</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#preprocessor-rule-other</string>
      </dict>
    </array>
    <key>fileTypes</key>
    <array>
      <string>pike</string>
      <string>pmod</string>
    </array>
    <key>name</key>
    <string>Pike</string>
    <key>keyEquivalent</key>
    <string>^~C</string>
  </dict>
</plist>